on: pull_request
name: Main
jobs:
  phpinsights:
    name: PHP-Insights
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: PHP-Insights
      uses: docker://tienvx/phpinsights-action
      with:
        args: "-v --min-quality=90 --min-architecture=80 --min-style=90"
